### PR TITLE
TinyMCE Controlled Inputs with React.js

### PR DESCRIPTION
**Pull request by HurricaneJames**
TinyMCE is not the best tool to use with React.js, let's just get that out there in the open. However, some of us are required to make it work. Personally, I hope that group of devs is limited to me, but I suspect not. Fortunately, I was mostly able to bend TinyMCE into a React controlled component mold. This talk will cover some of the problems I faced and how they were solved.

### CODE REVIEW

**Comment by jcsrb** [comment]
:+1:

**Comment by JedWatson** [comment]
Would love to see the source for this, the repo you've linked to is currently blank...

**Comment by HurricaneJames** [comment]
Shoot, I must have origin set to my home server. This is why I try to avoid doing things at 2am. I'll push out again when I get home this evening.

**Comment by HurricaneJames** [comment]
@JedWatson sorry for the delay. Surprising number of unexpected events led to delays before I could look at this. Fortunately, I had a few minutes tonight, so I wrote a quick readme, threw together an example, and posted it to GitHub and npm, [react-tinymce-input](https://github.com/HurricaneJames/react-tinymce-input). This is alpha or beta level code with no tests, so don't hesitate to make suggestions or point out bugs.

**Pull request closed without merging**
