### PR TITLE
Can components be truly encapsulated?

### PR DESCRIPTION
**Pull request by ovidiuch**
A talk about designing encapsulated React components, [Cosmos](https://github.com/skidding/cosmos) and a live demo with [Flatris](http://skidding.github.io/flatris/) components.

### CODE REVIEW

**Comment by kevinrobinson** [comment]
:+1:

**Comment by kastermester** [comment]
:+1:

**Comment by miklschmidt** [comment]
:+1:

**Comment by m64253** [comment]
:+1:

**Comment by johncotter** [comment]
:+1:

**Comment by moisadoru** [comment]
:+1:

**Comment by gaearon** [comment]
Yes! :+1:

**Comment by palcu** [comment]
:+1:

**Comment by emorikawa** [comment]
:+1:

**Comment by mbylstra** [comment]
:+1:

**Comment by mihneadb** [comment]
:+1:

**Comment by janmyler** [comment]
:+1:

**Comment by eddievlagea** [comment]
:+1:

**Comment by catalinmiron** [comment]
:+1:

**Comment by c7tincu** [comment]
:+1: :smile:

**Comment by petrbela** [comment]
:+1:

**Comment by ariabuckles** [comment]
:+1:

**Comment by bowd** [comment]
:+1:

**Comment by valer-cara** [comment]
:+1:

**Comment by piatra** [comment]
:+1:

**Comment by JedWatson** [comment]
:+1:

**Comment by RadValentin** [comment]
:+1:

**Pull request merged**
