### PR TITLE
Building the React Native Playground (http://rnplay.org)

### PR DESCRIPTION
**Pull request by jsierles**

### CODE REVIEW

**Comment by kevinrobinson** [comment]
@jsierles The playground is incredible for lowering the barrier to mobile development, particularly for teaching. much :heart:

**Comment by jsierles** [comment]
Cheers! By the time the conf comes around, I'm sure we'll have a lot more to show.

**Comment by AnSavvides** [comment]
:+1:

**Comment by petrbela** [comment]
:+1:

**Comment by jsierles** [comment]
This project, along with its iOS app, is now open sourced at https://github.com/rnplay

**Comment by johncotter** [comment]
:+1:

**Comment by HurricaneJames** [comment]
:+1:

**Comment by gaearon** [comment]
:+1:

**Comment by josephsavona** [comment]
:+1:

**Comment by chantastic** [comment]
:+1:

**Comment by andreaskeller** [comment]
:+1:

**Comment by JedWatson** [comment]
:+1:

**Comment by bruderstein** [comment]
:+1:

**Pull request merged**
