### PR TITLE
Brewfactory: Beer Brewing with Node and React

### PR DESCRIPTION
**Pull request by hekike**
Have you ever thought about how cool would it be to drink you own beer instead of the commercial ones?
This story is about us: beer lovers and techies:

> An IT engineer and a med student walks in to a bar. They get disappointed by the corn infested MegaBrews, so comes the motivation to put up a fight.

There is nothing hard in brewing your own beer, but some of the processes are really boring and time consuming if you don't automate it.
Because of this, me and a friend of mine built a semi-automated brewing machine what is powered by Node.js, SparkCore and React.js.
It runs in the cloud, collect logs, sends notifications and also has an isomorphic React client.

We call the project http://brewfactory.org/ and already brewed a huge amount of beer with that.
cheers! :beers:

### CODE REVIEW

**Comment by kastermester** [comment]
:+1: I like beer.

**Comment by miklschmidt** [comment]
:+1:

**Comment by tmoitie** [comment]
:+1: Did someone mention beer?

**Comment by m64253** [comment]
:+1:

**Comment by bjoreman** [comment]
:+1:

**Comment by HurricaneJames** [comment]
Will you have samples for everybody to try?

**Comment by hekike** [comment]
@HurricaneJames no sorry, sadly we are not brewing in that scale, and also would be hard to deliver it to the conf. But say hello when you are in Budapest and I'll gave you "samples" :)

**Comment by gergelyke** [comment]
:+1:

**Comment by petrbela** [comment]
:+1:

**Comment by vasarhelyia** [comment]
:+1:

**Comment by patcito** [comment]
Thanks for participating! Your proposal was awesome but we could only pick just a few.

**Pull request closed without merging**
