### PR TITLE
Going native with Este.js

### PR DESCRIPTION
**Pull request by grabbou**
Hey guys! Glad to be a part of React Europe, wanted to share with you couple of interesting things and design patterns we've learned when transitioning from React to React Native in Este.js community. During the 5 minutes talk, I am going to compare both React and React Native projects outlining the differences and showing how easily yet quickly you can transition any React app into the native world without dropping any of its features :)

### CODE REVIEW

**Comment by petrbela** [comment]
:+1: it's amazing how @steida's library/bootstrap became so popular so fast

**Comment by grabbou** [comment]
@petrbela before I met @steida I wasn't a big fun of Flux stuff at all. The first project that clearly convinced me to all React paradigms <3

**Comment by tajo** [comment]
:+1:

**Comment by steida** [comment]
:+1:

**Comment by kevinrobinson** [comment]
:+1:

**Comment by abtris** [comment]
:+1:

**Comment by conor** [comment]
:+1:

**Comment by ptica** [comment]
:+1:

**Comment by jsifalda** [comment]
:+1:

**Comment by miklschmidt** [comment]
:+1:

**Comment by karanbhangui** [comment]
:+1:

**Comment by andreaskeller** [comment]
:+1:

**Comment by PetrSnobelt** [comment]
:+1:

**Comment by JedWatson** [comment]
:+1:

**Comment by tomfrew** [comment]
:+1:

**Comment by alimek** [comment]
:+1:

**Comment by adampiotrowski** [comment]
:+1:

**Comment by mrcnkoba** [comment]
:+1:

**Comment by aedanexplosive** [comment]
:+1:

**Comment by radko93** [comment]
:+1:

**Comment by elkorn** [comment]
:+1:

**Comment by Yyystek** [comment]
:+1:

**Comment by Siguardius** [comment]
:+1:

**Comment by andrzejewsky** [comment]
:+1:

**Comment by miszu** [comment]
:+1:

**Comment by HereIsJohnny** [comment]
:+1:

**Pull request merged**
