### PR TITLE
Everything they don't tell you about context

### PR DESCRIPTION
**Pull request by bruderstein**
The undocumented but well known secret of context. Explained
without using the word "context"

### CODE REVIEW

**Comment by miklschmidt** [comment]
:+1:

**Comment by m64253** [comment]
:+1:

**Comment by kastermester** [comment]
:+1:

**Comment by tom** [comment]
:+1:

**Comment by parkji** [comment]
:+1:

**Comment by HurricaneJames** [comment]
:+1:

**Comment by gaearon** [comment]
:+1:

**Comment by elierotenberg** [comment]
:+1: (spoiler alert: its actually a hidden global)

**Comment by emorikawa** [comment]
:+1:

**Comment by gaearon** [comment]
shutterstock_25016035

**Comment by mbylstra** [comment]
:+1:

**Comment by janmyler** [comment]
:+1:

**Comment by bruderstein** [comment]
@gaearon :laughing:  that image is _awesome_ - where'd you find it, can I use it in case the talk is chosen? :wink:

**Comment by chantastic** [comment]
:+1:

**Comment by ariabuckles** [comment]
:+1:

**Comment by JedWatson** [comment]
@bruderstein I suspect that @gaearon might be referring to this tweet... https://twitter.com/sebmarkbage/status/603805482780884992

And I hope you _do_ use the image :smile:

**Comment by dougmcclurg** [comment]
:+1:

**Comment by tajo** [comment]
:+1:

**Comment by bruderstein** [comment]
@JedWatson yeah, I'd seen that thread, which is why I really liked the image! :-)

**Comment by DjebbZ** [comment]
Would be nice

**Comment by gaearon** [comment]
I just googled "wormhole"

**Comment by yukioo** [comment]
:+1:

**Comment by DJCordhose** [comment]
:thumbsup:

**Pull request merged**
