### PR TITLE
React Templates - Very cool templating tool

### PR DESCRIPTION
**Pull request by rommguy**
Lightning talk proposal on React-templates

### CODE REVIEW

**Comment by petrbela** [comment]
:+1: I had checked out react templates earlier and it's a really interesting solution (though after angular I'm a bit scared of all the logic hidden in directives).

**Comment by rommguy** [comment]
@petrbela We actually tried to use angular and we didn't like all the 'magic' behind the directives. That's why when we wrote React Templates we tried to make it as simple as possible, with as little code as we could. The 'directives' are very simple. Our dev group has been using this for our main product in the last 6 months and we love it. Also has great plugins for JetBrains IDEs

**Comment by petrbela** [comment]
Yeah the scope for what you need the `rt-` functions to do is definitely much easier than what they are used for in angular. We're actually evaluating RT as a solution for custom templates in our new displays library, as JSX Compiler is a really huge alternative (it's like 100 kB if I remember correctly).

**Comment by rommguy** [comment]
Cool, you are welcome to contact me if you decide to use it and want some recommendations and best practices. I will also be at the conference with our code base.

**Comment by mayaheim** [comment]
👍

**Pull request closed without merging**
