### PR TITLE
Store relationships made easy

### PR DESCRIPTION
**Pull request by miklschmidt**
At Secoya we've used React for about a year, and just recently brought flux into play. We found ourselves having lots of relationships between stores to separate concerns and avoid duplicate data/functionality, and quickly grew tired of manually fixing up code involving dereferencing id's through other stores. I came up with an easy way to handle relationships in my flux implementation, capacitor.js. In this talk i will go over how i did it, and touch on the advantages we've experienced by having easy access to store relationships without all the hassle.

Looking forward to meet you all in july!

### CODE REVIEW

**Comment by johncotter** [comment]
:+1:

**Comment by bruderstein** [comment]
:+1:

**Comment by kastermester** [comment]
:+1:

**Comment by miklschmidt** [comment]
I might go into how you can make recursive stores with inexpensive loop detection.

**Comment by patcito** [comment]
Thanks for participating! Your proposal was awesome but we could only pick just a few.

**Pull request closed without merging**
