### PR TITLE
d3 with React

### PR DESCRIPTION
**Pull request by AnSavvides**
In short, my lightning talk proposal is all about using d3 with React.

My aim is for this to be an open-ended talk that I will base around my own experiences. I'd love to hear what people would want to get out of this talk - nothing is set in stone, so I will happily make any adjustments to what I have in mind to cater for what people want to learn.

### CODE REVIEW

**Comment by kevinrobinson** [comment]
:+1: I'm a big fan of making visualizations with React using d3 helpers.

**Comment by miklschmidt** [comment]
:+1:

**Comment by tom** [comment]
:+1:

**Comment by kastermester** [comment]
:+1:

**Comment by johncotter** [comment]
:+1:

**Comment by gaearon** [comment]
:+1:

**Comment by vjo** [comment]
:+1:

**Comment by sevki** [comment]
:+1:

**Comment by maroshii** [comment]
:+1:

**Comment by josephsavona** [comment]
:+1:

**Comment by janmyler** [comment]
:+1:

**Comment by chantastic** [comment]
:+1:

**Comment by ovidiuch** [comment]
:+1:

**Comment by znation** [comment]
:+1:

**Comment by crw** [comment]
:+1:

**Comment by olimsaidov** [comment]
👍

**Comment by romseguy** [comment]
Food for thought http://formidablelabs.com/blog/2015/05/21/react-d3-layouts/

**Comment by andreaskeller** [comment]
:+1:

**Comment by braposo** [comment]
:+1:

**Comment by AnSavvides** [comment]
Thanks @romseguy that's very useful :)

**Comment by yukioo** [comment]
:+1:

**Comment by cateland** [comment]
👍🏻

**Comment by DJCordhose** [comment]
:thumbsup:

**Comment by pkatseas** [comment]
:+1:

**Comment by n1ghtmare** [comment]
:thumbsup:

**Comment by baer** [comment]
The concept is great but I have some experience with this and have found D3 neither to be written in a way that lets you have access to data as it's computed nor is it decomposed as consumable modules such that you can pull in the math without the rendering. Often a single method may for example be responsible for selecting data, transforming it and adding animations. 

I got a couple of graphs working in pure React using D3 to do the math but many were out of reach. Have you discovered something unique that would enable React to be used to generate an SVG using D3's math without it's rendering?

**Comment by miklschmidt** [comment]
I've played with it myself as well, came to the same conclusion as @baer. Hope you have some tricks up your sleeve :)

**Pull request merged**
